# Generated by Django 5.0.2 on 2024-03-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                ("bookauthor", models.CharField(max_length=20)),
                ("bookname", models.CharField(max_length=25)),
                ("bookid", models.IntegerField(primary_key=True, serialize=False)),
                ("published_date", models.DateField()),
                ("bookcost", models.IntegerField()),
            ],
        ),
    ]
